#! /usr/bin/env node
'use strict'
const fs = require('fs');
if (process.argv.length > 2){
    const args = process.argv.slice(2);
    args.forEach(file => {
    fs.readFile(file, 'utf-8', (err, data) => {
        if (err) {
        return err;
        } else {
        console.log(data);
        }
    })
    });
}else{
    console.log("toto");
}